### PR TITLE
Fixing synching backups

### PR DESCRIPTION
**Pull request by alaa-alsalehi**
We fix this issue and try the whole process to be sure it works just fine
Closing this issue #72 

We will appreciate if you check this as soon as possible @gavindsouza

### CODE REVIEW

**Comment by alaa-alsalehi** [comment]
@gavindsouza any update on this?

**Comment by gavindsouza** [comment]
@mymi14s has volunteered to maintain this project. He'll be driving further contributions/reviews.

**Comment by mymi14s** [comment]
@ServeMe your changes will be reviewed and merged if all checks have passed.

**Comment by mymi14s** [comment]
@ServeMe could you please add clear description of what the issue was and how it was fixed in the PR.
e.g: While try to do x, why was encountered and it prevented z from ..............
Issue was fixed by ..........

**Comment by alaa-alsalehi** [comment]
@mymi14s Travis CI has broken for a while now in this repo I do not know why
about the PR
we test the whole backup and restore process starting from synching the already backup and ending with restoring the backup and fixing any issue we face
we are using version 13

**Pull request merged**
